Vet clinic database: add "join table" for visits
amejid/vet-clinic pull request #4
Opened 2022-09-16 10:07 UTC by amejid

## Milestone 4: Add "join table" for visits

In this PR, the following were implemented:-

- Create many-to-many relationships

The queries look like the following:-

- Who was the last animal seen by William Tatcher?
![q1](https://user-images.githubusercontent.com/17243325/190614721-17e8ba87-3549-4b2b-845b-f46baf6bf1eb.PNG)
- How many different animals did Stephanie Mendez see?
![q2](https://user-images.githubusercontent.com/17243325/190614788-d690afd4-cfff-4b1d-8df6-affe11b5e8ef.PNG)
- List all vets and their specialties, including vets with no specialties.
![q3](https://user-images.githubusercontent.com/17243325/190614866-7e2c055d-13d3-4ef6-a017-e513ef50f32f.PNG)
- List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
![q4](https://user-images.githubusercontent.com/17243325/190614916-5e33d38a-e723-4af8-9ccb-01f79c6395a1.PNG)
- What animal has the most visits to vets?
![q5](https://user-images.githubusercontent.com/17243325/190614980-e0c8dae0-c692-4fc5-b49e-5f7afad1a50b.PNG)
- Who was Maisy Smith's first visit?
![q6](https://user-images.githubusercontent.com/17243325/190615054-96bfcb46-0a47-446e-b592-8e784911c478.PNG)
- Details for most recent visit: animal information, vet information, and date of visit.
![q7](https://user-images.githubusercontent.com/17243325/190615118-529a04a7-9a01-4f78-bd51-6ff115767c16.PNG)
- How many visits were with a vet that did not specialize in that animal's species?
![q8](https://user-images.githubusercontent.com/17243325/190615197-fda7e2fa-1885-4e3c-8fb5-2758753648a8.PNG)
- What specialty should Maisy Smith consider getting? Look for the species she gets the most.
![q9](https://user-images.githubusercontent.com/17243325/190615257-0f657941-f923-4de5-b2fc-ee38170821bd.PNG)

2022-09-16 10:22 UTC, Whoistolu requested changes
Hi @amejid 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 10:22 UTC, Whoistolu commented on queries.sql
> +GROUP BY species.name
- [ ] [REQUIRED] Great job @amejid , however, it looks like you skipped some parts of the project requirements that say you should create queries to answer the following questions in transactions:

- Who was the last animal seen by William Tatcher?
Kindly implement this to get the project approved.

2022-09-16 10:27 UTC, Rustamxon7 approved these changes
## Hello @amejid 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-16 10:28 UTC, merged

2022-10-14 11:12 UTC, amejid commented
Thank you for reviewing and approving my code.

2022-10-14 11:13 UTC, amejid commented on queries.sql
> +GROUP BY species.name
Thank you for reviewing my project, I will make the necessary corrections as suggested.